dist: xenial
language: cpp

addons:
  apt:
    packages:
      - clang
      - libc++-dev

script:
  - make -C tests -j 4 CXX=g++
  - make -C tests clean
  - make -C tests -j 4 CXX=clang++ CXXFLAGS=-stdlib=libc++
  - make -C bundle VERSION=$TRAVIS_BRANCH

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: bundle/md.hpp
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+.*
