dist: xenial
language: cpp

addons:
  apt:
    packages:
      - clang
      - libc++-dev

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: g++
      script: make -C tests -j 2 TAGS="*" CXX=g++

    - stage: test
      name: clang++
      script: make -C tests -j 2 TAGS="*" CXX=clang++ CXXFLAGS=-stdlib=libc++

    - stage: deploy
      script: make -C bundle VERSION=$TRAVIS_BRANCH
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: bundle/md.hpp
        skip_cleanup: true
        on:
          tags: true
          condition: $TRAVIS_TAG =~ v[0-9]+.*
